In [ ]:
import torch
from torch.utils.data import Dataset,DataLoader
from torch.utils.data import random_split
import torch.nn as nn
from torch.optim import SGD

In [ ]:
device=('cuda' if torch.cuda.is_available() else 'cpu')
device

'cpu'

In [ ]:
#y=wx+b
w=torch.tensor([3.0],requires_grad=True)
x=torch.tensor([4],dtype=torch.float32)
b=torch.tensor([5],requires_grad=True,dtype=torch.float32)

In [ ]:
y=w*x+b
y.backward()

In [ ]:
print(x.grad,w.grad,b.grad)

None tensor([4.]) tensor([1.])


In [ ]:
#z=log(3*x**2+5*x*y)
x=torch.tensor([2.0],requires_grad=True)
y=torch.tensor([3.0],requires_grad=True)
z=torch.log(3*x**2+5*x*y)
z.backward()
print(x.grad,y.grad)

tensor([0.6429]) tensor([0.2381])


In [ ]:
x=torch.tensor([2.0],requires_grad=True)
y=torch.tensor([3.0],requires_grad=True)
a=x
a.retain_grad()
b=3*a**2
b.retain_grad()
c=y
c.retain_grad()
d=5*a*c
d.retain_grad()
e=b+d
e.retain_grad()
z=torch.log(e)
z.retain_grad()
z.backward()
print(x.grad,y.grad)

tensor([0.6429]) tensor([0.2381])


For the following training data, build a linear regression model. Assume w and
b are
initialized with 1 and learning parameter is set to 0.001.
x = torch.tensor( [12.4, 14.3, 14.5, 14.9, 16.1, 16.9, 16.5, 15.4, 17.0, 17.9, 18.8, 20.3, 22.4,
19.4, 15.5, 16.7, 17.3, 18.4, 19.2, 17.4, 19.5, 19.7, 21.2])
y = torch.tensor( [11.2, 12.5, 12.7, 13.1, 14.1, 14.8, 14.4, 13.4, 14.9, 15.6, 16.4, 17.7, 19.6,
16.9, 14.0, 14.6, 15.1, 16.1, 16.8, 15.2, 17.0, 17.2, 18.6])
Assume learning rate =0.001. Plot the graph of epoch in x axis and loss in y axis.

In [ ]:
x = torch.tensor( [12.4, 14.3, 14.5, 14.9, 16.1, 16.9, 16.5, 15.4, 17.0, 17.9, 18.8, 20.3, 22.4, 19.4, 15.5, 16.7, 17.3, 18.4, 19.2, 17.4, 19.5, 19.7, 21.2])
y = torch.tensor( [11.2, 12.5, 12.7, 13.1, 14.1, 14.8, 14.4, 13.4, 14.9, 15.6, 16.4, 17.7, 19.6, 16.9, 14.0, 14.6, 15.1, 16.1, 16.8, 15.2, 17.0, 17.2, 18.6])

epochs=10
alpha=0.001

def forward(x):
  return w*x+b

w=torch.tensor([1.0],requires_grad=True)
b=torch.tensor([1.0],requires_grad=True)

for _ in range(epochs):
  error=0
  for i in range(len(x)):
    y_pred=forward(x[i])
    error+=(y[i]-y_pred)**2
  loss=error/len(x)
  loss.backward()
  with torch.no_grad():
    w-=alpha*w.grad
    b-=alpha*b.grad
  w.grad.zero_()
  b.grad.zero_()
  print(w,b,loss.item())


tensor([0.8878], requires_grad=True) tensor([0.9937], requires_grad=True) 10.153912544250488
tensor([0.8455], requires_grad=True) tensor([0.9913], requires_grad=True) 1.4566774368286133
tensor([0.8296], requires_grad=True) tensor([0.9904], requires_grad=True) 0.2217213660478592
tensor([0.8236], requires_grad=True) tensor([0.9900], requires_grad=True) 0.04636411741375923
tensor([0.8213], requires_grad=True) tensor([0.9899], requires_grad=True) 0.021464206278324127
tensor([0.8204], requires_grad=True) tensor([0.9898], requires_grad=True) 0.017928214743733406
tensor([0.8201], requires_grad=True) tensor([0.9897], requires_grad=True) 0.017425701022148132
tensor([0.8200], requires_grad=True) tensor([0.9897], requires_grad=True) 0.01735403947532177
tensor([0.8200], requires_grad=True) tensor([0.9897], requires_grad=True) 0.0173435527831316
tensor([0.8199], requires_grad=True) tensor([0.9897], requires_grad=True) 0.017341721802949905


Revise the linear regression model by defining a user defined class titled RegressionModel
with two parameters w and b as its member variables. Define a constructor to initialize w
and b with value 1. Define four member functions namely forward(x) to implement wx+b,
update() to update w and b values, reset_grad() to reset parameters to zero, criterion(y, yp)
to implement MSE Loss given the predicted y value yp and the target label y. Define an
object of this class named model and invoke all the methods. Plot the graph of epoch vs
loss by varying epoch to 100 iterations.

x = torch.tensor([5.0, 7.0, 12.0, 16.0, 20.0])
y = torch.tensor([40.0, 120.0, 180.0, 210.0, 240.0])
learning_rate = torch.tensor(0.001)


In [ ]:
x = torch.tensor( [12.4, 14.3, 14.5, 14.9, 16.1, 16.9, 16.5, 15.4, 17.0, 17.9, 18.8, 20.3, 22.4, 19.4, 15.5, 16.7, 17.3, 18.4, 19.2, 17.4, 19.5, 19.7, 21.2])
y = torch.tensor( [11.2, 12.5, 12.7, 13.1, 14.1, 14.8, 14.4, 13.4, 14.9, 15.6, 16.4, 17.7, 19.6, 16.9, 14.0, 14.6, 15.1, 16.1, 16.8, 15.2, 17.0, 17.2, 18.6])

learning_rate = torch.tensor(0.001)

class LinearRegression:
  def __init__(self):
    self.w=torch.rand([1],requires_grad=True)
    self.b=torch.rand([1],requires_grad=True)
  def forward(self,x):
    return self.w*x+self.b
  def update(self):
    self.w-=learning_rate*self.w.grad
    self.b-=learning_rate*self.b.grad
  def grad_zero(self):
    self.w.grad.zero_()
    self.b.grad.zero_()
  def criterion(self,y,y_pred):
    return (y-y_pred)**2

def one_epoch(model):
  error=0
  for i in range(len(x)):
    y_pred=model.forward(x[i])
    error+=model.criterion(y[i],y_pred)
  loss=error/len(x)
  loss.backward()
  with torch.no_grad():
    model.update()
  model.grad_zero()
  print(model.w,model.b,loss.item())

model=LinearRegression()

for _ in range(10):
  one_epoch(model)






tensor([0.7761], requires_grad=True) tensor([0.2725], requires_grad=True) 15.48741340637207
tensor([0.8284], requires_grad=True) tensor([0.2754], requires_grad=True) 2.20963716506958
tensor([0.8481], requires_grad=True) tensor([0.2765], requires_grad=True) 0.3242711126804352
tensor([0.8555], requires_grad=True) tensor([0.2770], requires_grad=True) 0.0565607026219368
tensor([0.8583], requires_grad=True) tensor([0.2771], requires_grad=True) 0.018547389656305313
tensor([0.8594], requires_grad=True) tensor([0.2772], requires_grad=True) 0.013149707578122616
tensor([0.8598], requires_grad=True) tensor([0.2772], requires_grad=True) 0.012383215129375458
tensor([0.8599], requires_grad=True) tensor([0.2772], requires_grad=True) 0.012274383567273617
tensor([0.8600], requires_grad=True) tensor([0.2772], requires_grad=True) 0.012258881703019142
tensor([0.8600], requires_grad=True) tensor([0.2772], requires_grad=True) 0.01225667167454958


Convert your program written in Qn 3 to extend nn.module in your model. Also override
the necessary methods to fit the regression line. Illustrate the use of Dataset and DataLoader
from torch.utils.data in your implementation. Use the SGD Optimizer torch.optim.SGD()


In [ ]:

x = torch.tensor( [12.4, 14.3, 14.5, 14.9, 16.1, 16.9, 16.5, 15.4, 17.0, 17.9, 18.8, 20.3, 22.4, 19.4, 15.5, 16.7, 17.3, 18.4, 19.2, 17.4, 19.5, 19.7, 21.2])
y = torch.tensor( [11.2, 12.5, 12.7, 13.1, 14.1, 14.8, 14.4, 13.4, 14.9, 15.6, 16.4, 17.7, 19.6, 16.9, 14.0, 14.6, 15.1, 16.1, 16.8, 15.2, 17.0, 17.2, 18.6])

device=('cuda' if torch.cuda.is_available() else 'cpu')

class MyDataset(Dataset):
  def __init__(self,x,y):
    self.x=x
    self.y=y
  def __len__(self):
    return len(self.x)
  def __getitem__(self,idx):
    return self.x[idx].to(device),self.y[idx].to(device)

dataset=MyDataset(x,y)

train_size=int(0.8*len(x))
test_size=len(x)-train_size

train_data,test_data=random_split(dataset,[train_size,test_size])

train_set=DataLoader(train_data,batch_size=1,shuffle=True)
test_set=DataLoader(test_data,batch_size=1,shuffle=False)


class LinearRegression(nn.Module):
  def __init__(self):
    super().__init__()
    self.w=torch.nn.Parameter(torch.rand([1]))
    self.b=torch.nn.Parameter(torch.rand([1]))
  def forward(self,x):
    return self.w*x+self.b

model=LinearRegression()
loss=nn.MSELoss()
optimizer=SGD(model.parameters(),lr=0.001)


def one_epoch():
  error=0
  for i,data in enumerate(train_set):
    input,label=data
    optimizer.zero_grad()
    output=model(input)
    loss1=loss(output,label)
    loss1.backward()
    optimizer.step()
    error+=loss1.item()
  return error/len(train_set)
print("Initial parameters:", [p.data for p in model.parameters()])

for _ in range (10):
  avg_loss=one_epoch()
  print(avg_loss)


print("Updated parameters:", [p.data for p in model.parameters()])

Initial parameters: [tensor([0.2117]), tensor([0.5646])]
7.806949597729828
0.022136433801279054
0.02067436209189408
0.02061143436569384
0.022871193155879155
0.021448425980957433
0.019722158447418932
0.02128152635648601
0.02099112931318814
0.021170544418257324
Updated parameters: [tensor([0.8482]), tensor([0.6023])]


In [ ]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset,DataLoader,random_split

x = torch.tensor( [12.4, 14.3, 14.5, 14.9, 16.1, 16.9, 16.5, 15.4, 17.0, 17.9, 18.8, 20.3, 22.4, 19.4, 15.5, 16.7, 17.3, 18.4, 19.2, 17.4, 19.5, 19.7, 21.2])
y = torch.tensor( [11.2, 12.5, 12.7, 13.1, 14.1, 14.8, 14.4, 13.4, 14.9, 15.6, 16.4, 17.7, 19.6, 16.9, 14.0, 14.6, 15.1, 16.1, 16.8, 15.2, 17.0, 17.2, 18.6])

class mydataset(Dataset):
  def __init__(self,x,y):
    self.x=x
    self.y=y
  def __len__(self):
    return len(self.x)
  def __getitem__(self,idx):
    return self.x[idx].to(device),self.y[idx].to(device)

dataset=mydataset(x,y)
train_size=int(0.7*len(x))
test_size=len(x)-train_size
train_set,test_set=random_split(dataset,[train_size,test_size])


train_data=DataLoader(train_set,batch_size=1,shuffle=True)
test_data=DataLoader(test_set,batch_size=1,shuffle=False)



class LinearRegression(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear=nn.Linear(1,1)
  def forward(self,x):
    return self.linear(x)

model=LinearRegression()
loss_fn=nn.MSELoss()
optimizer=torch.optim.SGD(model.parameters(),lr=0.001)

def one_epoch():
  total_loss=0
  for i,(input,label) in enumerate(train_data):
    optimizer.zero_grad()
    output=model(input)
    loss=loss_fn(output,label)
    loss.backward()
    optimizer.step()
    total_loss+=loss.item()
  return total_loss/len(train_data)

for _ in range(10):
  res=one_epoch()
  print(res,[p.data for p in model.parameters()])


4.859565337847016 [tensor([[0.8903]]), tensor([-0.3636])]
0.021480010194864008 [tensor([[0.8941]]), tensor([-0.3629])]
0.023787314224136935 [tensor([[0.8973]]), tensor([-0.3622])]
0.024705253563297447 [tensor([[0.8980]]), tensor([-0.3616])]
0.023219144004542613 [tensor([[0.8965]]), tensor([-0.3613])]
0.022224110866773117 [tensor([[0.8904]]), tensor([-0.3611])]
0.02501293554064432 [tensor([[0.8905]]), tensor([-0.3606])]
0.024996934049568154 [tensor([[0.8970]]), tensor([-0.3598])]
0.022019064701453317 [tensor([[0.8950]]), tensor([-0.3594])]
0.027375550467695575 [tensor([[0.8970]]), tensor([-0.3586])]


AttributeError: 'list' object has no attribute 'size'